# general
train_batch_size: 64
test_batch_size: 32

clients: 66

shape: !!python/tuple [0, 6, 1, 200]
num_classes: 12
in_channels: 6
# dim: 2880
dim: 12416


server_epochs: 200
client_epochs: 20
test_epochs: 1
note: ""
# learning rate
rate: 0.003
frac: 0.1

malicious_client: 34
attack_client: 7