# general
train_batch_size: 256
test_batch_size: 32

clients: 22

shape: !!python/tuple [0, 6, 1, 200]
num_classes: 12
in_channels: 6
# dim: 2880
dim: 12416


server_epochs: 200
client_epochs: 30
test_epochs: 1
note: ""
# learning rate
rate: 0.01
frac: 0.3

malicious_client: 14
attack_client: 7